const express = require("express");
const verifyProof = require("../utils/verifyProof");

const port = 1225;

const app = express();
app.use(express.json());

// hardcode a merkle root here representing the whole nice list
// paste the hex string in here, without the 0x prefix
// This Merkle Root was generated by instatiating a new MerkleTree(niceList)
// and calling the getRoot() function
const MERKLE_ROOT =
  "ddd59a2ffccddd60ff47993312821cd57cf30f7f14fb82937ebe2c4dc78375aa";

app.post("/gift", (req, res) => {
  // inserting parameters from the front-end here
  const body = req.body;
  const name = body.params.name;
  const proof = body.params.proof;
  // proving that the name is on the list
  let isInTheList = false;
  if (verifyProof(proof, name, MERKLE_ROOT)) {
    isInTheList = true;
  }
  if (isInTheList) {
    res.send("You get a toy robot!");
  } else {
    res.send("You are not on the list :(");
  }
});

app.listen(port, () => {
  console.log(`Listening on port ${port}!`);
});
